### ISSUE TITLE
Typeerror: List indices must be integers, not str

### ISSUE THREAD

**Issue by TrueDolphin** [jankais3r/DNoiSe#1]
Traceback (most recent call last):
File /DNoiSe.py, line 127, in <module>
       For a in parsed_all_queries["data"]
Typeerror: List indices must be integers, not str

**Comment by jankais3r** [comment]
This indicates that the response it got from your pi-hole is in a different format than what's expected. 
Can you put `print parsed_all_queries` on line 124 and post beginning of what you get? It should look like:
`{u'data': [[u'1553493369', u'A', u'e.crashlytics.com', u'192.168.1.93', u'1', u'0', u'4', u'7'],...`

**Comment by TrueDolphin** [comment]
User:# python ./DNoiSe.py
[]
Traceback (most recent call last):
File /DNoiSe.py, line 128, in
For a in parsed_all_queries["data"]
Typeerror: List indices must be integers, not str

**Comment by jankais3r** [comment]
You might have to temporarily comment out the problematic line so we can get the output.

**Comment by TrueDolphin** [comment]
Commented out the if statement, and same issue on line 138.
Which is the query_types section.

**Comment by jankais3r** [comment]
Comment that out as well. Since it’s using the same data it’s failing for the same reason. We need to see your pihole reply to figure out what’s wrong. Are you sure you put the correct auth key in the config section?

**Comment by TrueDolphin** [comment]
Ok, turns out pi-hole crashed when I first ran this script. Kinda odd.
Uncommented things and left the print, changed it to print to file, and it looks like your first response.

**Comment by jankais3r** [comment]
So all good now? Can I close the issue?
