### ISSUE TITLE
API Request Failed

### ISSUE THREAD

**Issue by djohnson4** [jankais3r/DNoiSe#5]
I put the API token from setupVars (matches what's on the web interface of pihole) into the script. This was the log.

> 2019-04-04 08:14:16 Got network connection.
> 2019-04-04 08:14:16 Downloading the domain listâ€¦
> 2019-04-04 08:14:17 Importing to sqliteâ€¦
> 2019-04-04 08:14:22 Done. It took 6s to download and process the list.
> 2019-04-04 08:14:22 API request failed. Retrying in 15 seconds.
> 2019-04-04 08:14:37 API request failed. Retrying in 15 seconds.

Even after reinstalling pihole . It worked a few days ago, then after restarting the server (on ubuntu) it started saying API request failed.

**Comment by jankais3r** [comment]
Try this to debug: https://github.com/jankais3r/DNoiSe/issues/1#issuecomment-476066103

Basically you want to print the variable that holds the complete URL, and then visit that URL from your browser and let us know what you see there.

**Comment by djohnson4** [comment]
It doesn't print. Stills ays API request failed

user@server:~/DNoiSe# python ./DNoiSe.py

^CTraceback (most recent call last):
  File "./DNoiSe.py", line 112, in <module>
    time.sleep(15)
KeyboardInterrupt

**Comment by djohnson4** [comment]
If I use

`http://pi.hole/admin/api.php?getAllQueries&auth=[api]`

I get the list of URLs.

Update: When it connects to example.com, it also doesn't show in pihole.

**Comment by jankais3r** [comment]
That’s clearly not the URL that DNoiSe is trying to access, as the correct one contains time range parameters.

**Comment by djohnson4** [comment]
Yes, I used that just to see if it was getting the list since it wasn't returning anything from print parsed_all_queries

I can put time ranges in there I guess but it's failing before that point so it shouldn't matter, no?

**Comment by djohnson4** [comment]
Was an issue with requests.
