### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olsenwc** [jankais3r/DNoiSe#6]
I followed the instructions on the readme file and received the following error:
Traceback (most recent call last):
  File "./DNoiSe.py", line 37, in <module>
    log_file = codecs.open(working_directory+"dnoise.log", mode="w", encoding="utf-8")
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/home/pi/dnoise.log'

**Comment by jankais3r** [comment]
The error says you don’t have a directory called /home/pi/

What machine are you running this on?

What do you get when you enter command `ls /home/pi`?

**Comment by olsenwc** [comment]
I am running this on ubuntu 18.04 lts

**Comment by jankais3r** [comment]
Then change the `working_directory = "/home/pi/"` part of the config section into a folder that actually exists. E.g. your user's home directory.

**Comment by olsenwc** [comment]
or should I put it in share where pi is?

**Comment by jankais3r** [comment]
Doesn't matter where you put it, just configure it with an existing path.

**Comment by olsenwc** [comment]
I am assuming that it is working now.
![image](https://user-images.githubusercontent.com/32272608/59980806-51ca9080-95c0-11e9-8618-c9e1060877c3.png)

**Comment by jankais3r** [comment]
Great, congrats! Closing the issue for now.

**Comment by olsenwc** [comment]
thanks
