### ISSUE TITLE
move configuration out to file

### ISSUE THREAD

**Issue by hunleyd** [jankais3r/DNoiSe#7]
Any chance you can add support for reading a config file so we don't need to edit the script directly when we want a different dir from /home/pi or have to use an IP other than 127.0.0.1 ?

**Comment by jankais3r** [comment]
Hi, this is probably not planned at this point. Besides adding support for Python3 I don't have any plans to update this script, therefore there is no downside to having config directly in the script (compared to a case when there would be frequent updates - in such case it would certainly make sense to have a standalone config file).
